from . import owner
from . import prop
from . import type
from . import buyer
from . import tag
from . import offer
from . import transaction
from . import maintenance
from . import res_partner
from . import lease
from . import account_move
from . import document
from . import visitor
from . import work_order
from . import survey
from . import property_availability
from . import property_media
